# Generated by Django 4.1.6 on 2023-02-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_review_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='post',
            new_name='product',
        ),
    ]
